# Site Information
site_name: Jacob's House
site_url: https://dev3l.github.io/jacobs-house/
site_author: Jason
site_description: "A structured, supportive program for rebuilding lives in recovery."

# Theme Configuration
theme:
  name: material
  palette:
    primary: "blue" # Calm and stable primary color
    accent: "orange" # Warm secondary accent for highlights
    scheme: "slate" # Accessible dark background with high-contrast elements
  font:
    text: "Lato" # Modern and readable sans-serif font for body text
    code: "Fira Code" # Clean monospace font for code blocks
  favicon: "images/favicon.png"
  logo: "images/logo.png"

# Navigation Structure
nav:
  - Home: index.md
  - About: about.md
  - Impact: impact.md
  - Programs:
      - Programs Overview: programs/programs.md
      - Transition Housing: programs/transition-housing.md
      - Sober Living: programs/sober-living.md
      - Advanced Living: programs/advanced-living.md
  - Contact: contact.md

# Plugins
plugins:
  - search
  - macros
  - ultralytics:
      verbose: true
      enabled: true
      add_desc: true
      add_image: true
      add_keywords: true
      add_json_ld: true
      add_css: true
  - minify_html

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - overrides/footer.js
